def slangwords(kalimat):
    replacements = {
        'ad': 'ada',
        'ampe': 'sampai',
        'bg': 'bang',
        'bgt': 'banget',
        'brp': 'berapa',
        'byk': 'banyak',
        'dlm': 'dalam',
        'dl': 'dll',
        'dn': 'dan',
        'donk': 'dong',
        'dpt': 'dapat',
        'drmh': 'dirumah',
        'duit': 'uang',
        'gimana': 'bagaimana',
        'gmn': 'bagaimana',
        'jaman': 'zaman',
        'jg': 'juga',
        'jt': 'juta',
        'km': 'kamu',
        'kn': 'kan',
        'ko': 'kok',
        'krn': 'karena',
        'org': 'orang',
        'pake': 'pakai',
        'pcrn': 'pacaran',
        'pengen': 'ingin',
        'ptg': 'penting',
        'rezky': 'rezeki',
        'sist': 'sista',
        'skrng': 'sekarang',
        'slu': 'selalu',
        'sm': 'sama',
        'smg': 'semoga',
        'smkn': 'semakin',
        'tau': 'tahu',
        'tgl': 'tinggal',
        'tlp': 'telepon',
        'tp': 'tapi',
        'tsb': 'tersebut',
        'udah': 'sudah',
        'wa': 'whatsapp',
        'yg': 'yang',
        'ky': 'seperti',
        'kyk': 'seperti',
        'rb': 'ribu',
        'rban': 'ribu',
        'aja': 'saja',
        'ajah': 'saja',
        'ajh': 'saja',
        'yu': 'yuk',
        'skuy' : 'yuk',
        'kuy': 'yuk',
        'yo': 'yuk',
        'yok': 'yuk',
        'aq': 'aku',
        'ak': 'aku',
        'gw': 'aku',
        'kak': 'kakak',
        'ka': 'kakak',
        'kaka': 'kakak',
        'faham': 'paham',
        'fahami': 'paham',
        'kalo': 'kalau',
        'klo': 'kalau',
        'banget': 'sekali',
        'bgt': 'sekali',
        'bgd': 'sekali',
        'lagi': 'sedang',
        'lg': 'sedang',
        'sdg': 'sedang',
        'kalo': 'kalau',
        'klw': 'kalau',
        'kl': 'kalau',
        'skrg': 'sekarang',
        'sekrg': 'sekarang',
        'terima kasih': 'terimakasih',
        'makasih': 'terimakasih',
        'mksh': 'terimakasih',
        'thanks': 'terimakasih',
        'thx': 'terimakasih',
        'ga': 'tidak',
        'gk': 'tidak',
        'gak': 'tidak',
        'ngga': 'tidak',
        'nggak': 'tidak',
        'nda': 'tidak',
        'mw': 'mau',
        'mo': 'mau',
        'ntar': 'nanti',
        'ntr': 'nanti',
        'dg': 'dengan',
        'dgn': 'dengan',
        'hy': 'hai',
        'hi': 'hai',
        'jgn': 'jangan',
        'jn': 'jangan',
        'ges': 'guys',
        'gaes': 'guys',
        'fol': 'follow',
        'folow': 'follow',
        'folower': 'follow',
        'folowernya': 'follow',
        'follower': 'follow',
        'folowers': 'follow',
        'followers': 'follow',
        'cuma': 'hanya',
        'cuman': 'hanya',
        'drpd': 'daripada',
        'keburu': 'buru',
        'bu':'ibu'
    }
    words = kalimat.split(' ')
    for i, word in enumerate(words):
        words[i] = replacements.get(word, word)

    return " ".join(words)

#print(slangwords('hi ges jgn ky itu'))